/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_turn_fusionio_FusionIOAPI */

#ifndef _Included_com_turn_fusionio_FusionIOAPI
#define _Included_com_turn_fusionio_FusionIOAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_init_jni_cache
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1init_1jni_1cache
  (JNIEnv *, jclass);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_open
 * Signature: (Lcom/turn/fusionio/Store;ILcom/turn/fusionio/FusionIOAPI$ExpiryMode;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1open
  (JNIEnv *, jclass, jobject, jint, jobject, jint);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_close
 * Signature: (Lcom/turn/fusionio/Store;)V
 */
JNIEXPORT void JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1close
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_store_info
 * Signature: (Lcom/turn/fusionio/Store;)Lcom/turn/fusionio/StoreInfo;
 */
JNIEXPORT jobject JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1store_1info
	(JNIEnv *env, jclass cls, jobject _store);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_or_create_pool
 * Signature: (Lcom/turn/fusionio/Store;Ljava/lang/String)Lcom/turn/fusionio/Pool;
 */
JNIEXPORT jobject JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1or_1create_1pool
	(JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_all_pools
 * Signature: (Lcom/turn/fusionio/Store;)[Lcom/turn/fusionio/Pool;
 */
JNIEXPORT jobjectArray JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1all_1pools
	(JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_delete_pool
 * Signature: (Lcom/turn/fusionio/Pool;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1delete_1pool
	(JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_delete_all_pools
 * Signature: (Lcom/turn/fusionio/Store;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1delete_1all_1pools
	(JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_alloc
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1alloc
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_free_value
 * Signature: (Lcom/turn/fusionio/Value;)V
 */
JNIEXPORT void JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1free_1value
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_value_len
 * Signature: (Lcom/turn/fusionio/Pool;Lcom/turn/fusionio/Key;)I
 */
JNIEXPORT jint JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1value_1len
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_key_info
 * Signature: (Lcom/turn/fusionio/Pool;Lcom/turn/fusionio/Key;)I
 */
JNIEXPORT jobject JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1key_1info
	(JNIEnv *env, jclass cls, jobject _pool, jobject _key);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get
 * Signature: (Lcom/turn/fusionio/Pool;Lcom/turn/fusionio/Key;Lcom/turn/fusionio/Value;)I
 */
JNIEXPORT jint JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_put
 * Signature: (Lcom/turn/fusionio/Pool;Lcom/turn/fusionio/Key;Lcom/turn/fusionio/Value;)I
 */
JNIEXPORT jint JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1put
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_exists
 * Signature: (Lcom/turn/fusionio/Pool;Lcom/turn/fusionio/Key;Lcom/turn/fusionio/KeyValueInfo;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1exists
  (JNIEnv *, jclass, jobject, jobject, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_delete
 * Signature: (Lcom/turn/fusionio/Pool;Lcom/turn/fusionio/Key;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1delete
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_delete_all
 * Signature: (Lcom/turn/fusionio/Store;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1delete_1all
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_batch_put
 * Signature: (Lcom/turn/fusionio/Pool;[Lcom/turn/fusionio/Key;[Lcom/turn/fusionio/Value;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1batch_1put
  (JNIEnv *, jclass, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_iterator
 * Signature: (Lcom/turn/fusionio/Pool;)I
 */
JNIEXPORT jint JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1iterator
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_next
 * Signature: (Lcom/turn/fusionio/Pool;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1next
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_current
 * Signature: (Lcom/turn/fusionio/Pool;ILcom/turn/fusionio/Key;Lcom/turn/fusionio/Value;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1current
  (JNIEnv *, jclass, jobject, jint, jobject, jobject);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_end_iteration
 * Signature: (Lcom/turn/fusionio/Pool;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1end_1iteraton
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_turn_fusionio_FusionIOAPI
 * Method:    fio_kv_get_last_error
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_turn_fusionio_FusionIOAPI_fio_1kv_1get_1last_1error
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
